steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend:${SHORT_SHA}'
      - '--cluster=analytics-cluster'
      - '--location=us-central1'
      - '--namespace=analytics'

options:
  logging: CLOUD_LOGGING_ONLY
