steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend'

  # Deploy to GKE - update image only, preserve existing deployment config
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/analytics-frontend'
      - 'nextjs=us-central1-docker.pkg.dev/${PROJECT_ID}/analytics/analytics-frontend:${SHORT_SHA}'
      - '--namespace=analytics'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=analytics-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
